CREATE TABLE IF NOT EXISTS orders (
    order_uid  uuid PRIMARY KEY NOT NULL,
    track_number VARCHAR(255),
    entry VARCHAR(255),
    locale VARCHAR(255),
    internal_signature VARCHAR(255),
    customer_id VARCHAR(255),
    delivery_service VARCHAR(255),
    shardkey VARCHAR(255),
    sm_id BIGINT,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    oof_shard VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS deliveries (
    delivery_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_uid   uuid REFERENCES orders (order_uid) UNIQUE,
    name VARCHAR(255),
    phone VARCHAR(255),
    zip VARCHAR(255),
    city VARCHAR(255),
    address VARCHAR(255),
    region VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction   uuid REFERENCES orders (order_uid) UNIQUE,
    request_id VARCHAR(255),
    currency VARCHAR(255),
    provider VARCHAR(255),
    amount BIGINT,
    payment_dt BIGINT,
    bank VARCHAR(255),
    delivery_cost BIGINT,
    goods_total BIGINT,
    custom_fee BIGINT
);

CREATE TABLE IF NOT EXISTS items (
     item_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     order_uid    uuid REFERENCES orders (order_uid),
     chrt_id BIGINT,
     track_number VARCHAR(255),
     price BIGINT,
     rid VARCHAR(255),
     name VARCHAR(255),
     sale BIGINT,
     size VARCHAR(255),
     total_price BIGINT,
     nm_id BIGINT,
     brand VARCHAR(255),
     status BIGINT
);